apiVersion: v1
kind: Service
metadata:
  name: hello-app-springboot
spec:
  selector:
    app: hello-app-springboot
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32002
