apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app-python
  template:
    metadata:
      labels:
        app: hello-app-python
    spec:
      containers:
        - name: hello-app-python
          image: harshit200525/python-app1
          # envFrom:
          #   - configMapRef:
          #       name: app-config
          #   - secretRef:
          #       name: db-secret
          env:
            - name: ENV_VALUE
              valueFrom:
                  configMapKeyRef:
                      name: python-app-config
                      key: ENV_VALUE
            - name: PORT
              valueFrom:
                  secretKeyRef:
                      name: python-db-secret
                      key: PORT
          ports:
            - containerPort: 3000