# services:
#     service-a:
#         build:
#           context: ./node/service-a
#           dockerfile: Dockerfile
#         depends_on:
#             - service-b
#         ports:
#             - 3100:3000
#         environment:
#             - TAX_SERVICE_URL=http://service-b:4000


#     service-b:
#       build:
#           context: ./node/service-b
#           dockerfile: Dockerfile
#       ports:
#             - 3200:4000



services:
    service-a:
        build:
          context: ./spring/service-a
          dockerfile: Dockerfile
        depends_on:
            - service-b
        ports:
            - 3100:3000
        environment:
            - TAX_SERVICE_URL=http://service-b:4000


    service-b:
      build:
          context: ./spring/service-b
          dockerfile: Dockerfile
      ports:
            - 3200:4000

                   